### ISSUE TITLE
Phoenix/Docker setup questions

### ISSUE THREAD

**Issue by pendletons** [cjbottaro/faktory_worker_ex#17]
I'm trying to get Faktory working within a Phoenix umbrella app that also uses Docker.

I've setup `docker-compose.yml` as follows:
```yaml
app:
  links:
    - faktory

faktory:
  image: contribsys/faktory:latest
  ports:
    - "7419:7419"
    - "7420:7420"
```

Docker starts up, but I'm struggling with getting everything else to recognise the faktory service as running. If I don't add any configuration for Faktory in `config.exs` then it tries to talk to `localhost:7419` when it should talk to `faktory:7419` (as it's a different Docker container).

If I add this to `config.exs`:
```yaml
config :faktory_worker_ex, MyApp.FaktoryClient,
  adapter: Faktory.Configuration.Client,
  host: System.get_env("FAKTORY_HOST") || "faktory",
  port: System.get_env("FAKTORY_PORT") || "7419",
  pool: System.get_env("FAKTORY_POOL") || 10
```

and this to `lib/my_app/faktory_client.ex`:
```elixir
defmodule MyApp.FaktoryClient do
   use Faktory.Configuration.Client
end
```

and this to `lib/my_app/application.ex`:
```elixir
def start(_type, _args) do
  # Define workers and child supervisors to be supervised
  children = [
    # Start the endpoint when the application starts
    supervisor(MyApp.Endpoint, []),
    supervisor(MyApp.FaktoryClient, [])
  ]
end
```

then it complains that it cannot start `MyApp.FaktoryClient`
```
app_1       | ** (Mix) Could not start application faktory_worker_ex: Faktory.Application.start(:normal, []) returned an error: shutdown: failed to start child: Faktory.Supervi
sor.Clients
app_1       |     ** (EXIT) shutdown: failed to start child: MyApp.FaktoryClient
app_1       |         ** (EXIT) an exception was raised:
app_1       |             ** (MatchError) no match of right hand side value: {:error, {:function_clause, [{:inet_tcp, :getserv, ["tcp://172.17.0.2:7419"], [file: 'inet_tcp.erl'
, line: 55]}, {:gen_tcp, :connect1, 4, [file: 'gen_tcp.erl', line: 158]}, {:gen_tcp, :connect, 4, [file: 'gen_tcp.erl', line: 145]}, {Faktory.Tcp, :connect, 1, [file: 'lib/fakt
ory/tcp.ex', line: 30]}, {Faktory.Connection, :do_connect, 1, [file: 'lib/faktory/connection.ex', line: 91]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]},
 {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
app_1       |                 (poolboy) /usr/src/app/deps/poolboy/src/poolboy.erl:275: :poolboy.new_worker/1
app_1       |                 (poolboy) /usr/src/app/deps/poolboy/src/poolboy.erl:296: :poolboy.prepopulate/3
app_1       |                 (poolboy) /usr/src/app/deps/poolboy/src/poolboy.erl:145: :poolboy.init/3
app_1       |                 (stdlib) gen_server.erl:365: :gen_server.init_it/2
app_1       |                 (stdlib) gen_server.erl:333: :gen_server.init_it/6
app_1       |                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
app_1       | [error] GenServer #PID<0.780.0> terminating
```

Any thoughts? I'm sure it's something super basic but I've read the hexdocs a few times and don't see anything else to try.

Thanks in advance. :)
